<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Cs\FLG.Cs.Datamodel\FLG.Cs.Datamodel.csproj" />
    <ProjectReference Include="..\..\Cs\FLG.Cs.Decorators\FLG.Cs.Decorators.csproj" />
    <ProjectReference Include="..\..\Cs\FLG.Cs.Framework\FLG.Cs.Framework.csproj" />
    <ProjectReference Include="..\..\Cs\FLG.Cs.ServiceLocator\FLG.Cs.ServiceLocator.csproj" />
  </ItemGroup>

</Project>
